---
title: "bayesianBirdModel"
author: ""
date: "17 May 2018"
output: pdf_document
---

# Overview
Still to do:
1. Need to use the 'data' rds ("https://drive.google.com/open?id=1KoL6QzKqCiBUZ8i6O-llCiit0G2APWLI"), as the Minidataset*.csv doesn't have all information. However: this one is a list already. Need to be rbindlisted (only forestry ones, both scales) and duplicated lines excluded.
2. Add age to this "final" dataset. Should do all prep (step 1) in a new function before passing to dataframeBuilding.
3. Correct age2004 for correct age based on the column YYYY
4. dataframeBuilding function needs to make a list with copies of all the values of the model and the specific bird sp offset and log and count (bird names on the cols): each element of the named list is a data.frame with all info for one bird species
5. Do data checking on Age?
6. Create the data.frame that I want to populate:

Abundance = NA (the one parameter to monitor!),
estimate = log of estimate based on LCC_BCR (I have this table somewhere!),
age = corrected growth 1985-2011 based off of 2004 layer (and maybe double check the disturbances?! See item 5.),
disturbance = values from the focal rasterstack, 
X = coordenadas X from "template raster" (one of the mergedFocal?) for all pixels to forecast (maybe would be smart to crop to only the pixels that are within Sp distribution for computation time?),
Y = same as x,
offsets = NA

7. Put the DF in the model and figure out after that...
# NOT SUREIT IS WORTH IT SEPARATE EACH YEAR OR DO THE WHOLE PREDICTION FOR ALL YEARS... Might be too heavy?!
# Usage

```{r module_usage}
library("SpaDES")

setPaths(modulePath = file.path(getwd(), "modules"))
getPaths() # shows where the 4 relevant paths are
invisible(sapply(X = list.files(file.path(getwd(), "functions"), full.names = TRUE), FUN = source))

times <- list(start = 1985, end = 1985)

parameters <- list(
)

modules <- list("bayesianBirdModel")

rp <- Cache(defineStudyArea, testArea = TRUE, 
                          specificTestArea = "boreal",
                          mapSubset = "Alberta")

.objects <- list("rP" = rp,
                 "birdSpecies" = c("BBWA", "BOCH"))
inputs <- list()
outputs <- list()

bayes <- simInitAndSpades(times = times, params = parameters, modules = modules,
                 objects = .objects, debug = 2)

```

      # Observations
      #   Not sure negative binomial is the best one… Maybe ZIP would be better? 
      #   We can try extra-Poisson dispersion model (ie. 12.3.3. Kery and Schaub 2012), 
      #   negative binomial (Kery and Royle 2016) or even regular Poisson (depends really 
      #   on the species we are dealing with… I don’t think Poisson is the best for old-forest 
      #   associated birds!).
      #   
      #   We could eventually model time (HH MM) as RE of propability of observation
      
      # Obvious outcomes
      #   NN > NL
      # Wrong! The observation per se is at local scale. NN would only indicate the observation at local scale with Ndisturbance!
      # Therefore we use the offsets here, to correct back for counts, and on the NL we don't, as we have already counts entered as a 
      # covariate. 
      
      
      #   # Assumptions
      # 1. Bird density might vary depending on cluster (RE)
      # 2. Bird density might vary depending on the year (RE)
      

