---
title: "gettingDataFromSQL"
author: "Tati Micheletti"
date: "7/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Connecting to the SQL

To connect to the SQL, make sure you have a working connection to the SQL. If you don't have, check with BAM manager and 
.rmd file `settingUpMicrosoftSQLServerInLinux.rmd` if working from Linux.

```{r loading_libs}
library(reproducible)
reproducible::Require("DBI")
reproducible::Require("odbc")
#reproducible::Require("RODBC") # Not sure it is needed. If anything fails, use it
con <- DBI::dbConnect(odbc::odbc(),
                      Driver   = "/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so", # Path for the location of driver for Linux
                      Server   = "boreal.biology.ualberta.ca", # Connect to BAM Server
# Note: even though the address is set up in Windows as boreal.biology.ualberta.ca\boreal, in R I need to exclude the \boreal
                      Database = "BAM_National_V4_2015_0206", # Got the names from the Windows ODBC connection
                      UID      = "michelet",#rstudioapi::askForPassword("Database User"),
                      PWD      = "Univ3rs!ty",#rstudioapi::askForPassword("Database Password"),
                      Port     = 1433)
```

## Checking out the tables

```{r tables}
tableVersion <- "V4_2015" # This should be passed in global
colPKEY <- c("PCODE", "METHOD", "ROUND", "YYYY", "JULIAN", "SS", "PKEY", "SITE", "STN")
colXY <- c("PCODE", "SS", "X", "Y") #, "BOR_LOC"
colPtCount <- c("PCODE", "SS", "PKEY", "SPECIES", "ABUND", "DURATION", "DISTANCE", "BEH") # Included for making the OFFSETS module
# "SELECT * FROM cars WHERE BOR_LOC LIKE ''"

tablesNames <- DBI::dbListTables(con, table_name = paste0("%", tableVersion,"%"))

XYTableName <- tablesNames[grepl(pattern = "XY", x = tablesNames)]
PtCountTableName <- tablesNames[grepl(pattern = "PtCount", x = tablesNames)]
PKEYTableName <- tablesNames[grepl(pattern = "PKEY", x = tablesNames)]

# listFields <- dbListFields(con, PKEYTableName) # List fields in the table
# Retrieve XY to use from Alberto's table to 
queryXY <- dbSendQuery(con, paste0("SELECT * FROM ", XYTableName)) #, "WHERE BOR_LOC LIKE"
queryPtCount <- dbSendQuery(con, paste0("SELECT * FROM ", PtCountTableName))
queryPKEY <- dbSendQuery(con, paste0("SELECT * FROM ", PKEYTableName))

XY <- DBI::dbFetch(queryXY) %>% 
  data.table::data.table()
PtCount <- DBI::dbFetch(queryPtCount) %>%
  data.table::data.table()
PKEY <- DBI::dbFetch(queryPKEY) %>%
  data.table::data.table()
```

