---
title: "Understanding Alberto's GIS Prep"
author: "Tati Micheletti"
date: "June 15, 2018"
output: html_document
---

Based on what he did in his `Process of selecting points (with ArcGIS steps).docx`:

1. Created disturbance shapefiles by year (2001-2014) from Hansen, removing the fire disturbances (using Canadian National  Fire  Database  and  the  Alaska  Fire  History  Database).  Files: N/A
2. Creates **cumulative** shapefiles of cover loss from this dataset. *WHY?*
    - Files: `~/gisdata/GFW/Without burnt polygons/lossyear_XXXX.shp`
3. 'From  BEAD  linear  and  polygonal  I  erased  the  polygons  from  Hansen  until  2012' to create a baseline disturbance for 2000. Files: `~/gisdata/BEAD/BEAD_2000_polygonal`;  `~/gisdata/BEAD/BEAD_2000_linear`)  
4. From BAM dataset, selected only the points from 2000 and before 2014, within the boreal region, projected, and buffered to 100m and 500m (which is 100-500m, not 0-500m), and reprojected to Albers Conic. Also calculated 100m and 500m buffer area.  
5. Intersected `BEAD_2000` (baseline?) with BAM dataset right before buffering. File: BAM_100_BEAD_2000.shp  
6. Dissolved  by  PKEY  (I think here it puts together all species and makes each station unique)
7. Calculated the area (BEAD_100_A and BEAD_500_A) of disturbance 
 ~ STOPPED IN POINT "Intersections with BEAD" point 3 because I don't know what the atttribute table is exporting to all BAM points... Know now. I think it was about Agents of disturbance... But stopped here.
